spring:
  profiles:
    active: local

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    redis:
      timeout: 10000


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_REDIRECT_URI}
            scope:
              - profile
              - email
        provider:
          google:
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
  refresh-expiration: 604800000
