#application-prod.yml
spring:
  config:
    activate:
      on-profile: prod

  application:
    name: booktown-prod

  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: https://booktown.site/login/oauth2/code/google
          kakao:
            redirect-uri: https://booktown.site/login/oauth2/code/kakao
          naver:
            redirect-uri: https://booktown.site/login/oauth2/code/naver